[package]
name = "account_manager"
version = "0.1.0"
edition = "2021"
authors = [ "Niels F. S. Vistisen" ]

[dependencies]
axum = "0.6.12"
axum-test-helper = "0.2.0"
clap = { version = "4.1.14", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
sha256 = "1.1.2"
